version: '3.9'

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - static_volume:/home/enigma_group/web/staticfiles
        command: gunicorn enigma_group.wsgi:application --bind 0.0.0.0:8000
        expose:
            - '8000'
        stdin_open: true
        tty: true
        depends_on:
            - db
    db:
        image: postgres:16rc1-alpine3.18
        stdin_open: true
        tty: true
        environment:
            POSTGRES_DB: 'enigma_group_db'
            POSTGRES_USER: 'enigma_group_user'
            POSTGRES_PASSWORD: 'Pk12342341'
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/enigma_group/web/staticfiles
        ports:
            - "1337:80"
        stdin_open: true
        tty: true
        restart: always
        depends_on:
            - web
volumes:
    postgres_data:
    static_volume: